apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: configuration-registry
spec:
  compositeTypeRef:
    apiVersion: kndp.io/v1alpha1
    kind: Registry
  resources:


    - name: registry-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              type: kubernetes.io/dockerconfigjson
              data:
                .dockerconfigjson: ""
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.kubernetesProviderCfgRef
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-registry"
          toFieldPath: metadata.name
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.username
              - fromFieldPath: spec.password
            strategy: string
            string:
              fmt: "%s:%s"
          transforms:
            - type: string
              string:
                type: Convert
                convert: "ToBase64"
          toFieldPath: metadata.annotations[auth]
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[auth]
          toFieldPath: status.auth
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.server
              - fromFieldPath: spec.username
              - fromFieldPath: spec.password
              - fromFieldPath: spec.email
              - fromFieldPath: status.auth
            strategy: string
            string:
              fmt: '{"auths":{"%s":{"username":"%s","password":"%s","email":"%s","auth":"%s"}}}'
          transforms:
            - type: string
              string:
                type: Convert
                convert: "ToBase64"
          toFieldPath: spec.forProvider.manifest.data[.dockerconfigjson]


    - name: kyverno-policy-scplc
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: kyverno.io/v1
              kind: ClusterPolicy
              spec:
                generateExisting: true
                rules:
                  - name: kndp-sync-registry-secrets
                    match:
                      resources:
                        kinds:
                          - Namespace
                    generate:
                      apiVersion: v1
                      kind: Secret
                      synchronize: true
                      name: ""
                      namespace: "{{request.object.metadata.name}}"
                      clone:
                        name: ""
                        namespace: ""
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.kubernetesProviderCfgRef
        toFieldPath: spec.providerConfigRef.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.name
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-scplc"
        toFieldPath: metadata.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.namespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
      - type: FromCompositeFieldPath
        fromFieldPath: spec.name
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-scplc"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.name
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-scplc"
        toFieldPath: spec.forProvider.manifest.spec.rules[0].generate.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.name
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-scplc"
        toFieldPath: spec.forProvider.manifest.spec.rules[0].generate.clone.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.namespace
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-scplc"
        toFieldPath: spec.forProvider.manifest.spec.rules[0].generate.clone.namespace


    - name: kyverno-policy-imgplc
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: kyverno.io/v1
              kind: ClusterPolicy
              metadata:
                name: ""
              spec:
                generateExisting: true
                rules:
                  - name: kndp-add-imagepullsecret
                    match:
                      any:
                        - resources:
                            kinds:
                              - Pod
                    skipBackgroundRequests: false
                    mutate:
                      patchStrategicMerge:
                        spec:
                          containers: []
                          imagePullSecrets:
                            - name: ""
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.kubernetesProviderCfgRef
        toFieldPath: spec.providerConfigRef.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.name
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-imgplc"
        toFieldPath: metadata.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.namespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
      - type: FromCompositeFieldPath
        fromFieldPath: spec.name
        transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-imgplc"
        toFieldPath: spec.forProvider.manifest.metadata.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.images
        toFieldPath: spec.forProvider.manifest.spec.rules[0].mutate.patchStrategicMerge.spec.containers
      - type: FromCompositeFieldPath
        fromFieldPath: spec.imagePullSecrets
        toFieldPath: spec.forProvider.manifest.spec.rules[0].mutate.patchStrategicMerge.spec.imagePullSecrets

