apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: registries.kndp.io
spec:
  group: kndp.io
  names:
    kind: Registry
    plural: registries
    singular: registry
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
                server:
                  type: string
                token:
                  type: string
                images:
                  type: array
                  items:
                    type: object
                    properties:
                      <(image):
                        type: string
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                kubernetesProviderCfgRef:
                  type: string
            status:
              type: object
              description: Status information.
              properties:
                    auth:
                      type: string

      served: true
      referenceable: true