apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: localregistries.kndp.io
spec:
  group: kndp.io
  names:
    kind: LocalRegistry
    plural: localregistries
    singular: localregistry
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
                nodePort:
                  type: string
                kubernetesProviderCfgRef:
                  type: string
            status:
              type: object
              description: Status information.


      served: true
      referenceable: true