name: Release builds

on:
  push:
    tags:
    - '*'
    
permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ vars.GITHUB_REF_NAME }}
        skipIfReleaseExists: true
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/kndp"
        binary_name: "kndp"
        ldflags: -X "main.Version=${{ env.APP_VERSION }}"
  oci-builds:
    name: build OCI images
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/kndpio/cli
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
    - uses: actions/checkout@v4
    - name: Set VERSION env
      run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - uses: ko-build/setup-ko@v0.6
      env:
        KO_DOCKER_REPO: ${{ env.REGISTRY }}
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: |
        ko build ./cmd/kndp/ --tags=${{ env.VERSION }} --bare